// src/components/CorrectiveMaintenancePrintable.tsx

import React from 'react';

interface CorrectiveMaintenanceRecord {
  id: string;
  assetName: string;
  maintenanceType: string;
  status: string;
  cost: number;
  date: any; // Can be a string or a Firestore Timestamp
  description?: string;
  assignedTo?: string;
  systemType?: string;
  frequency?: string;
  materialsNeeded?: string[];
}

interface Props {
  record: CorrectiveMaintenanceRecord | null;
}

/**
 * Component rendered by react-to-print for a corrective maintenance record.
 * MUST be wrapped in React.forwardRef so the library can grab the DOM node.
 */
export const CorrectiveMaintenancePrintable = React.forwardRef<HTMLDivElement, Props>(
  ({ record }, ref) => {
    if (!record) {
      return null;
    }

    const maintenanceDate = record.date?.seconds
      ? new Date(record.date.seconds * 1000)
      : new Date(record.date);

    return (
      <div ref={ref} className="p-10 font-sans text-base text-gray-800">
        <header className="mb-8 border-b-2 border-gray-300 pb-4">
          <h1 className="text-3xl font-bold text-gray-900">Corrective Maintenance Report</h1>
          <p className="text-lg text-gray-600">Asset: {record.assetName}</p>
        </header>

        <main className="space-y-6">
          <div className="grid grid-cols-2 gap-x-8 gap-y-4">
            <div>
              <p className="text-sm font-semibold text-gray-500">Maintenance Type</p>
              <p className="font-medium">{record.maintenanceType}</p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-500">Status</p>
              <p className="font-medium text-green-600">{record.status}</p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-500">Maintenance Date</p>
              <p className="font-medium">{maintenanceDate.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-500">System Type</p>
              <p className="font-medium">{record.systemType || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-500">Assigned To</p>
              <p className="font-medium">{record.assignedTo || 'N/A'}</p>
            </div>
             <div>
              <p className="text-sm font-semibold text-gray-500">Total Cost</p>
              <p className="font-medium">${Number(record.cost).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
            </div>
          </div>
          
          <div className="pt-4">
            <h3 className="text-xl font-semibold mb-2 border-b pb-2">Details</h3>
            <div>
              <h4 className="font-semibold mt-4">Description of Work Performed:</h4>
              <p className="mt-1 text-gray-700 whitespace-pre-wrap">{record.description || 'No description provided.'}</p>
            </div>
            <div>
              <h4 className="font-semibold mt-4">Materials Needed:</h4>
              {record.materialsNeeded && record.materialsNeeded.length > 0 ? (
                <ul className="list-disc list-inside mt-1 pl-4 text-gray-700">
                  {record.materialsNeeded.map((material, index) => (
                    <li key={index}>{material}</li>
                  ))}
                </ul>
              ) : (
                <p className="mt-1 text-gray-600">No materials listed.</p>
              )}
            </div>
          </div>
        </main>
        
        <footer className="mt-10 pt-4 border-t text-center text-xs text-gray-500">
          <p>Generated by Facility-Flow-Nexus</p>
          <p>This is an automated report. All details are based on the data entered into the system.</p>
        </footer>
      </div>
    );
  }
);

CorrectiveMaintenancePrintable.displayName = "CorrectiveMaintenancePrintable";